services:
  back:
    build:
      context: .
    networks:
      - reverse-proxy
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/back
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  database:
    image: postgres:16.3
    networks:
      - reverse-proxy
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: back
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root

networks:
  reverse-proxy:
